figure;
subplot(1,2,1);
plot(time,piston);
title('Piston position-Minjun');
subplot(1,2,2);
plot(time,mold);
title('Mold position-Minjun');
subplot(1,2,1);
ylim([-0.015,0.015]);
xlim([7,10]);
subplot(1,2,2);
xlim([7,10]);
xlabel('time (s)');
ylabel('mold position (m)');
subplot(1,2,1);
xlabel('time (s)');
ylabel('piston position (m)');
